### ISSUE TITLE
It went wrong when clone an Error

### ISSUE THREAD

**Issue by miserylee** [pvorb/node-clone#67]
``` javascript
const error = new Error('hhhhhh');
console.log(error);
/*
 Error: hhhhhh
 at Object.<anonymous> (/Users/miserylee/Documents/projects/com.whxxcy.8ddao/test.js:3:15)
 at Module._compile (module.js:541:32)
 at Object.Module._extensions..js (module.js:550:10)
 at Module.load (module.js:458:32)
 at tryModuleLoad (module.js:417:12)
 at Function.Module._load (module.js:409:3)
 at Module.runMain (module.js:575:10)
 at run (bootstrap_node.js:352:7)
 at startup (bootstrap_node.js:144:9)
 at bootstrap_node.js:467:3
 */
console.log(clone(error));
/*
 [Error]
 */
```

**Comment by pvorb** [comment]
This should be fixed in v2.1.0
